-- Oracle Database 26ai Vector Search Setup

-- 1. Create the RAG table with a VECTOR column
-- The dimension 768 matches Vertex AI text-embedding-004
CREATE TABLE RAG_TAB (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONTENT CLOB,
    METADATA JSON,
    EMBEDDING VECTOR(768, FLOAT32)
);

-- 2. Create a Vector Index for faster similarity search
-- Note: Requires Oracle Database 26ai or higher
CREATE VECTOR INDEX rag_tab_vec_idx ON RAG_TAB (EMBEDDING)
ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE DOT_PRODUCT
WITH TARGET ACCURACY 95;

-- 3. Verify the table
DESC RAG_TAB;
