set serveroutput on size unlimited

prompt [1/12] gc_suppliers
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE gc_suppliers (
            supplier_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_name       VARCHAR2(200) NOT NULL,
            tier_level          NUMBER(2) DEFAULT 1 NOT NULL,
            region_code         VARCHAR2(100) NOT NULL,
            on_time_pct         NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created gc_suppliers');
exception
    when object_exists then
        dbms_output.put_line('SKIP: gc_suppliers already exists');
    when others then
        dbms_output.put_line('FAIL: gc_suppliers -> ' || sqlerrm);
        raise;
end;
/

prompt [2/12] gc_plants
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE gc_plants (
            plant_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plant_name         VARCHAR2(200) NOT NULL,
            cycle_days          NUMBER(6,2),
            utilization_pct     NUMBER(5,2),
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created gc_plants');
exception
    when object_exists then
        dbms_output.put_line('SKIP: gc_plants already exists');
    when others then
        dbms_output.put_line('FAIL: gc_plants -> ' || sqlerrm);
        raise;
end;
/
