set serveroutput on size unlimited

prompt [1/10] gc_suppliers
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE gc_suppliers (
            supplier_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_name       VARCHAR2(200) NOT NULL,
            tier_level          NUMBER(2) DEFAULT 1 NOT NULL,
            region_code         VARCHAR2(100) NOT NULL,
            on_time_pct         NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created gc_suppliers');
exception
    when object_exists then
        dbms_output.put_line('SKIP: gc_suppliers already exists');
    when others then
        dbms_output.put_line('FAIL: gc_suppliers -> ' || sqlerrm);
        raise;
end;
/

prompt [2/10] gc_plants
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE gc_plants (
            plant_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plant_name         VARCHAR2(200) NOT NULL,
            cycle_days          NUMBER(6,2),
            utilization_pct     NUMBER(5,2),
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created gc_plants');
exception
    when object_exists then
        dbms_output.put_line('SKIP: gc_plants already exists');
    when others then
        dbms_output.put_line('FAIL: gc_plants -> ' || sqlerrm);
        raise;
end;
/

prompt [3/10] sc_ports
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_ports (
            port_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            port_name          VARCHAR2(200) NOT NULL,
            eta_hours          NUMBER(6,2),
            delay_risk_score   NUMBER(5,2),
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_ports');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_ports already exists');
    when others then
        dbms_output.put_line('FAIL: sc_ports -> ' || sqlerrm);
        raise;
end;
/

prompt [4/10] sc_warehouses
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_warehouses (
            warehouse_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            warehouse_name     VARCHAR2(200) NOT NULL,
            inventory_units    NUMBER(10) DEFAULT 0,
            fill_rate_pct      NUMBER(5,2),
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_warehouses');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_warehouses already exists');
    when others then
        dbms_output.put_line('FAIL: sc_warehouses -> ' || sqlerrm);
        raise;
end;
/

prompt [5/10] sc_products
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_products (
            product_id         VARCHAR2(64) PRIMARY KEY,
            product_name       VARCHAR2(200) NOT NULL,
            demand_change_pct  NUMBER(5,2) DEFAULT 0,
            margin_pct         NUMBER(5,2) DEFAULT 0,
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_products');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_products already exists');
    when others then
        dbms_output.put_line('FAIL: sc_products -> ' || sqlerrm);
        raise;
end;
/

prompt [6/10] sc_routes
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_routes (
            route_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            origin_type        VARCHAR2(50) NOT NULL,
            origin_id          NUMBER NOT NULL,
            destination_type   VARCHAR2(50) NOT NULL,
            destination_id     NUMBER NOT NULL,
            transport_mode     VARCHAR2(50) DEFAULT 'SEA',
            transit_days       NUMBER(6,2),
            cost_per_ton       NUMBER(10,2),
            risk_factor        NUMBER(5,2) DEFAULT 0
        )
    ]';
    dbms_output.put_line('OK: created sc_routes');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_routes already exists');
    when others then
        dbms_output.put_line('FAIL: sc_routes -> ' || sqlerrm);
        raise;
end;
/

prompt [7/10] sc_shipments
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_shipments (
            shipment_id        VARCHAR2(64) PRIMARY KEY,
            product_id         VARCHAR2(64) NOT NULL REFERENCES sc_products(product_id),
            origin_name        VARCHAR2(200),
            destination_name   VARCHAR2(200),
            quantity           NUMBER(10) NOT NULL,
            status             VARCHAR2(50) DEFAULT 'IN_TRANSIT',
            eta_days           NUMBER(6,2),
            risk_score         NUMBER(5,2) DEFAULT 0,
            shipped_at         TIMESTAMP DEFAULT SYSTIMESTAMP
        )
    ]';
    dbms_output.put_line('OK: created sc_shipments');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_shipments already exists');
    when others then
        dbms_output.put_line('FAIL: sc_shipments -> ' || sqlerrm);
        raise;
end;
/

prompt [8/10] sc_disruptions
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_disruptions (
            disruption_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            location_name      VARCHAR2(200) NOT NULL,
            disruption_type    VARCHAR2(100) NOT NULL,
            severity           VARCHAR2(32) DEFAULT 'MEDIUM',
            impact_score       NUMBER(5,2) DEFAULT 0,
            active_flag        CHAR(1) DEFAULT 'Y' NOT NULL
        )
    ]';
    dbms_output.put_line('OK: created sc_disruptions');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_disruptions already exists');
    when others then
        dbms_output.put_line('FAIL: sc_disruptions -> ' || sqlerrm);
        raise;
end;
/

prompt [9/10] Property Graph: supply_chain_pg (SQL Property Graph in 23ai / 26ai)
declare
    pg_exists exception;
    pragma exception_init(pg_exists, -955);
begin
    execute immediate q'[
        CREATE PROPERTY GRAPH supply_chain_pg
        VERTEX TABLES (
            gc_suppliers KEY (supplier_id) LABEL Supplier
                PROPERTIES (supplier_id, supplier_name, tier_level, region_code, on_time_pct),
            gc_plants KEY (plant_id) LABEL Plant
                PROPERTIES (plant_id, plant_name, cycle_days, utilization_pct),
            sc_ports KEY (port_id) LABEL Port
                PROPERTIES (port_id, port_name, eta_hours, delay_risk_score),
            sc_warehouses KEY (warehouse_id) LABEL Warehouse
                PROPERTIES (warehouse_id, warehouse_name, inventory_units, fill_rate_pct)
        )
        EDGE TABLES (
            sc_routes KEY (route_id)
                SOURCE KEY (origin_id) REFERENCES sc_ports (port_id)
                DESTINATION KEY (destination_id) REFERENCES sc_warehouses (warehouse_id)
                LABEL CONNECTS_TO
                PROPERTIES (route_id, transport_mode, transit_days, cost_per_ton, risk_factor)
        )
    ]';
    dbms_output.put_line('OK: created property graph supply_chain_pg');
exception
    when pg_exists then
        dbms_output.put_line('SKIP: supply_chain_pg already exists');
    when others then
        dbms_output.put_line('NOTE: Property Graph DDL skipped (requires Oracle 23ai+ PGQL support): ' || sqlerrm);
end;
/

prompt [10/10] Schema setup complete.
